Vision document
fga-eps-mds/2020.1-stay-safe-docs pull request #10
Opened 2020-08-22 19:12 UTC by tsrrodrigues

Vision Document

## Issue #
Close the issue #2 

## Description
This Pull Request creates the product's Vision Document.

2020-08-22 21:06 UTC, renan601 requested changes
O documento ficou muito bom, parabéns pessoal

Só tenho três considerações a fazer 
A primeira é que na parte do histórico de versões, vocês começaram a nomear a partir da versão 1.0 sem ter um documento completo e pronto. 
Quando estamos falando da versão 1.0 de algo é esperado que ele contenha todos os tópicos devidamente preenchidos, caso contrário você coloca essa versão como 0.1, 0.2, 0.3...... até finalizar o documento e ter a versão 1.0
Caso vocês façam pequenas modificações no doc mais pra frente teremos a versão 1.1, 1.2 e assim segue
Se a alteração for grande é possível definir uma nova versão como 2.0
Em resumo, o que vocês concluiram foi a versão 1.0 do documento

A segunda consideração é um erro de sintaxe, vi o termo vizualização algumas vezes no documento sendo que o correto é visualização.

A terceira consideração é em relação as referências, vocês utilizaram documentos de visão de outros grupos para tal e isso não é uma boa prática visto que os outros grupos também estão em processo de aprendizado, recomendo olhar as referências dos grupos que vocês citam (caso elas estejam corretas) e inclui-las.

Corrigindo esses pontos eu aprovo o PR

2020-08-23 01:50 UTC, brendavsantos commented
> O documento ficou muito bom, parabéns pessoal
> 
> Só tenho três considerações a fazer
> A primeira é que na parte do histórico de versões, vocês começaram a nomear a partir da versão 1.0 sem ter um documento completo e pronto.
> Quando estamos falando da versão 1.0 de algo é esperado que ele contenha todos os tópicos devidamente preenchidos, caso contrário você coloca essa versão como 0.1, 0.2, 0.3...... até finalizar o documento e ter a versão 1.0
> Caso vocês façam pequenas modificações no doc mais pra frente teremos a versão 1.1, 1.2 e assim segue
> Se a alteração for grande é possível definir uma nova versão como 2.0
> Em resumo, o que vocês concluiram foi a versão 1.0 do documento
> 
> A segunda consideração é um erro de sintaxe, vi o termo vizualização algumas vezes no documento sendo que o correto é visualização.
> 
> A terceira consideração é em relação as referências, vocês utilizaram documentos de visão de outros grupos para tal e isso não é uma boa prática visto que os outros grupos também estão em processo de aprendizado, recomendo olhar as referências dos grupos que vocês citam (caso elas estejam corretas) e inclui-las.
> 
> Corrigindo esses pontos eu aprovo o PR

Corrigi os erros de sintaxe e de acordo com uma conversa privada decidimos deixar as referências, pelo menos por enquanto.

2020-08-23 18:53 UTC, silvasara commented
Algumas alterações:
- [ ] Mudar o título do documento pra apenas "Documento de Visão";
- [ ] teremos mais documentos futuramente, então recomendo mudar o nome do arquivo de "index.md" para "visao.md" para facilitar a identificação;
- [ ] o arquivo com nome de "index.md" é o que fica na pagina de home, então deixem um arquivo com esse nome, mesmo que esteja vazio, para que não dê 404 na página inicial;
- [ ] acrescentar a página do doc de visão no arquivo "mkdocs.yml" dessa forma:
![image](https://user-images.githubusercontent.com/30883179/90984725-3a34c200-e54d-11ea-9e3b-ca945dc21566.png)
- [ ] Aproveitar e mudar o "site_name" no arquivo acima, separar com espaço as palavras do nome do app.
- [ ] Não é bom abrir o arquivo e a primeira coisa vista é uma tabela de versão, essa tabela é apenas de interesse interno do grupo, não interessa ao leitor. O melhor lugar pra ela ficar é no final do arquivo
- [ ] A melhor posição pras referências é no final, sendo o último tópico
- [ ] Os tópicos 1.1 e 1.5 estão um pouco redundantes, recomendo 'misturar' os textos dos dois tópicos e deixar como um tópico só no começo
- [ ] As primeirsas linhas da tabela 2.2 e 2.3 estão marcadas como se fossem títulos da coluna, e acredito que não sejam títulos

2020-08-23 19:04 UTC, silvasara requested changes
Algumas alterações:
- [x] Mudar o título do documento pra apenas "Documento de Visão";
- [x] teremos mais documentos futuramente, então recomendo mudar o nome do arquivo de "index.md" para "visao.md" para facilitar a identificação;
- [x] o arquivo com nome de "index.md" é o que fica na pagina de home, então mantenham como está na master
- [x] Não é bom abrir o arquivo e a primeira coisa vista é uma tabela de versão, essa tabela é apenas de interesse interno do grupo, não interessa ao leitor. O melhor lugar pra ela ficar é no final do arquivo
- [x] A melhor posição pras referências é no final, sendo o último tópico
- [x] Os tópicos 1.1 e 1.5 estão um pouco redundantes, recomendo 'misturar' os textos dos dois tópicos e deixar como um tópico só no começo
- [ ] As primeirsas linhas da tabela 2.2 e 2.3 estão marcadas como se fossem títulos da coluna, e acredito que não sejam títulos
- [x] As tabelas de resumo das partes interessadas e de resumo do usuário não são necessárias

2020-08-24 16:05 UTC, herickport commented
> Algumas alterações:
> 
> * [ ]  Mudar o título do documento pra apenas "Documento de Visão";
> * [ ]  teremos mais documentos futuramente, então recomendo mudar o nome do arquivo de "index.md" para "visao.md" para facilitar a identificação;
> * [ ]  o arquivo com nome de "index.md" é o que fica na pagina de home, então mantenham como está na master
> * [ ]  Não é bom abrir o arquivo e a primeira coisa vista é uma tabela de versão, essa tabela é apenas de interesse interno do grupo, não interessa ao leitor. O melhor lugar pra ela ficar é no final do arquivo
> * [ ]  A melhor posição pras referências é no final, sendo o último tópico
> * [ ]  Os tópicos 1.1 e 1.5 estão um pouco redundantes, recomendo 'misturar' os textos dos dois tópicos e deixar como um tópico só no começo
> * [ ]  As primeirsas linhas da tabela 2.2 e 2.3 estão marcadas como se fossem títulos da coluna, e acredito que não sejam títulos
> * [ ]  As tabelas de resumo das partes interessadas e de resumo do usuário não são necessárias

Em relação ao penúltimo tópico, acredito que o markdown no github não aceita tabelas sem cabeçalho, por isso a primeira linha aparece como título das colunas, mesmo não sendo.

2020-08-24 19:04 UTC, herickport commented
Com exceção da questão das referências, que foi decidido manter por enquanto, e do cabeçalho das tabelas 2.2 e 2.3, que é uma "exigência" do markdown, todos os demais pontos apresentados de sintaxe, conflito ou alterações foram corrigidos. Aguardo revisão.

2020-08-24 19:57 UTC, silvasara approved these changes

2020-08-25 04:51 UTC, renan601 approved these changes

2020-08-25 06:28 UTC, merged