Added sprint 6 documents
fga-eps-mds/2020.1-stay-safe-docs pull request #69
Opened 2020-10-04 03:14 UTC by renan601

## Issue #67 

## Description
Added sprint 6 planning, risks and review documents.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2020-10-04 06:18 UTC, silvasara requested changes

2020-10-04 06:18 UTC, silvasara commented on docs/sprints/sprint-6/sprint6-planning.md
> +**Membros Presentes:** Todos
Put absent members in the planning meeting

2020-10-04 06:18 UTC, silvasara commented on docs/sprints/sprint-6/sprint6-review.md
> +**Membros Presentes:** Todos
Put absent members in the review meeting

2020-10-04 06:18 UTC, silvasara commented on docs/sprints/sprint-6/sprint6-review.md
> +![Histórico de Contribuição Secretary-Service](../../images/sprints/sprint-5/ContributionGraph-Secretary.png "Histórico de Contribuição Secretary-Service")
The images are not being displayed

2020-10-08 08:13 UTC, silvasara approved these changes

2020-10-08 11:59 UTC, herickport approved these changes

2020-10-08 12:00 UTC, merged