Create acceptance test result document
fga-eps-mds/2020.1-stay-safe-docs pull request #94
Opened 2020-11-14 04:05 UTC by brendavsantos

Co-authored-by: Tiago <tsrrodrigues@outlook.com>

## Issue 
Resolves #93 

## Description
The document details the results of the acceptance tests and the decisions made from them.

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## How to validate?
Reading the document.

2020-11-14 17:31 UTC, silvasara requested changes
- Put the two documents about the tests in one folder, to improve the organization in mkdocs
- Update documents with the new tasks that have been added
- Change the title of the first test document, so that it does not become an "introdução" in mkdocs
- Provides a more conclusive analysis on each question and perhaps more qualitative, use the graphs e the responses of forms (I suggest not separating by tester but by questions)

2020-11-14 17:31 UTC, silvasara commented on docs/produto/acceptance-test-result.md
> +Baseado no [documento de aceitação](https://github.com/fga-eps-mds/2020.1-stay-safe-docs/blob/master/docs/produto/acceptance-test.md) foram realizados testes com 7(sete) pessoas para testarem as func
Place the link to production documentation on github pages

2020-11-14 17:35 UTC, rossicler approved these changes

2020-11-14 22:52 UTC, silvasara requested changes
- The new tasks were placed on the table but were not placed on the list.
- Rename the folder to be in Portuguese
- As the documents will be inside the folder, you can take the name "Teste de aceitação" from the documents:
![image](https://user-images.githubusercontent.com/30883179/99158559-dab10300-26b2-11eb-9ac9-be3a2fb07e7b.png)

2020-11-15 04:29 UTC, renan601 approved these changes

2020-11-16 13:09 UTC, silvasara approved these changes

2020-11-16 13:09 UTC, merged